### PR TITLE
rename es to elasticsearch

### PR DESCRIPTION
**Pull request by ebattat**
Rename all modules, classes, methods name from es to elasticsearch

### CODE REVIEW

**Comment by jeniferh** [comment]
seeing a few more:
https://github.com/redhat-performance/benchmark-runner/blob/857c72ff33ab9e54e52ffb4da88067df8e732849/benchmark_runner/benchmark_operator/benchmark_operator_workloads.py#L54  and 109,175,223,292,363

https://github.com/redhat-performance/benchmark-runner/blob/857c72ff33ab9e54e52ffb4da88067df8e732849/benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py#L202 and 270

**Comment by ebattat** [comment]
@jeniferh, Fixed. Can you please verify it ?

**Comment by jeniferh** [comment]
ok last ones I think:
https://github.com/redhat-performance/benchmark-runner/blob/4081c0c8d6aaa174d42996f5c34ed60fa56aede6/benchmark_runner/benchmark_operator/benchmark_operator_workloads_operations.py#L57 and 256,258,280,282

**Comment by ebattat** [comment]
@jeniferh, rename only modules, classes, methods not variables.
I prefer to keep the variables short.
What do you think ?

**Comment by jeniferh** [comment]
Ah ok my search went too far then, sounds good to me :)

**Comment by ebattat** [comment]
OK @jeniferh Thx, I will merge it.

**Pull request merged**
