### PR TITLE
Add command line options

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Add command line parsing.  Still under development.

### CODE REVIEW

**Comment by RobertKrawitz** [comment]
Yes, I also need to update HOWTO.md.  Meanwhile, could you review the actual code?

**Review by ebattat — COMMENTED** [review]
The code LGTM, need to check that it keep backward comparability and all the environment variables are working properly.

**Comment by RobertKrawitz** [comment]
Yep.  I'm just going to add examples of each way inside HOWTO.md the files in the docs directory.  I don't see a need to add a file just to show how the CLI is used -- that's all going to be familiar to developers.

**Comment by RobertKrawitz** [comment]
Added documentation.  Checked compatibility by running stressng_pod with both command line and environment options.

**Review by ebattat — APPROVED** [review]
/LGTM

**Pull request merged**
