### PR TITLE
add uperf 2 threads support

### PR DESCRIPTION
**Pull request by ebattat**
Add 2 threads support in uperf & update grafana dashboard report

### CODE REVIEW

**Review by RobertKrawitz — COMMENTED** [review]
What is benchmark-runner-report doing in here?

**Comment by ebattat** [comment]
@RobertKrawitz, I have just update the time to last 24 hours

**Comment by RobertKrawitz** [comment]
> @RobertKrawitz, I have just updated the time to last 24 hours in grafana report.

Why is that in the repo?

**Comment by ebattat** [comment]
@RobertKrawitz yes that related to benchmark-runner grafana dashboard

**Review by RobertKrawitz — APPROVED** [review]
lgtm

**Comment by RobertKrawitz** [comment]
/lgtm
/approve
Please merge

**Pull request merged**
