### PR TITLE
Stressng perf_ci "large" config

### PR DESCRIPTION
**Pull request by jeniferh**
- Change VM vcpu topology to sockets
 - Add perf_ci run type to stress "full" system (~75% host cpu, ~50% host mem, 5min run)

### CODE REVIEW

**Comment by jeniferh** [comment]
I tested on the Perf cluster, pod and vm types run fine for the new large perf_ci config but kata had a problem, it scheduled fine but appeared to die before the run completed, I will need to dig into it more tomorrow..

**Review by RobertKrawitz — APPROVED** [review]
Looks fine on the form; I'm going to trust you on the content.

**Review by ebattat — COMMENTED** [review]
/LGTM
Need to rebase before merging

**Review by ebattat — COMMENTED** [review]
/LGTM
/Approved

**Review by ebattat — APPROVED** [review]
/LGTM
/Approved

**Comment by jeniferh** [comment]
Thanks. Kata was dying prematurely for larger stressng vm_bytes values (I'd like to eventually understand why..) but I did some comparisons and larger values don't impact the mem bogomips result much, so just dropping it to stress ~50% of host memory which passes fine.

**Comment by RobertKrawitz** [comment]
> Thanks. Kata was dying prematurely for larger stressng vm_bytes values (I'd like to eventually understand why..) but I did some comparisons and larger values don't impact the mem bogomips result much, so just dropping it to stress ~50% of host memory which passes fine.

What exactly does vm_bytes do?  It might have been getting oom killed (by default, kata VMs have 2GiB).

**Comment by jeniferh** [comment]
> What exactly does vm_bytes do? It might have been getting oom killed (by default, kata VMs have 2GiB).
It is the amount the test mmaps, but it should have had plenty of room since the pod limit was significantly larger.. so a bit puzzling.

**Comment by RobertKrawitz** [comment]
How much?

**Comment by jeniferh** [comment]
The failure was vm_bytes=75G w/ 90Gi req/limit. What is working now is vm_bytes=60G w/ 75Gi req/limit. In the failure case, the kata pod would get scheduled, start the test & mem allocation but it would just go into pod 'Complete' state much earlier than the 5min runtime and the pod logs had no additional info. I didn't have a chance yet to catch exactly what amount of allocation triggered it, and probably need to figure out where the kata qemu logs reside as well.

**Pull request merged**
