### PR TITLE
Fix jenkinsfile workload retry

### PR DESCRIPTION
**Pull request by ebattat**
## Type of change
Note: Fill **x** in []
- [ ] bug
- [x] enhancement
- [ ] documentation
- [ ] dependencies

## Description

Enhance the capability to proceed to the next workload after three retry attempts for each workload

### CODE REVIEW

**Review by RobertKrawitz — COMMENTED** [review]
What was the problem before?

**Comment by ebattat** [comment]
Whole job was failed after 3 retries, this fix give the ability to continue to the next workload ...

**Comment by RobertKrawitz** [comment]
> Whole job was failed after 3 retries, this fix give the ability to continue to the next workload ...

Did the previous code not do that correctly?

**Comment by ebattat** [comment]
Yes, as I said the whole job was failed and didnt continue to the next workload

**Review by RobertKrawitz — APPROVED** [review]
I see what's going on -- the retryCount was basically ignored and the initial failure treated as a hard failure.

**Pull request merged**
