### PR TITLE
Update Grafana Dashboard

### PR DESCRIPTION
**Pull request by kelchen123**
Fixes:

1. Replaced old PerfCI-Regression-Summary.json file in perf folder with newly exported PerfCI grafana dashboard
2. Added FuncCI-Regression-Summary.json file in func folder, containing newly exported FuncCI grafana dashboard 
3. Deleted regression-summary.json and benchmark-runner-ci-status-report.json files from func folder

### CODE REVIEW

**Review by ebattat — COMMENTED** [review]
Please change Pr name to meaningful name as 'update grafana dashboard'

**Comment by kelchen123** [comment]
> Please change Pr name to meaningful name as 'update grafana dashboard'

done!

**Comment by ebattat** [comment]
@kelchen123, I have updated the Grafana dashboard, can you please update the latest version ?
[Please rebase it before pull]

**Review by ebattat — APPROVED** [review]
/LGTM

**Pull request merged**
