### PR TITLE
remove coredns patch

### PR DESCRIPTION
**Pull request by ebattat**
Remove coredns patch because removing bufsize from /etc/coredns/Corefile

### CODE REVIEW

**Comment by ebattat** [comment]
After discuss it with @RobertKrawitz, understand that its no harm to leave it in case of installing OCP 4.10 or older versions.

**Comment by jeniferh** [comment]
Sounds good to leave as is, and glad to see the issue is resolved in newer OCP versions.

**Comment by ebattat** [comment]
@RobertKrawitz, do you think we need to close this PR or leave it as is ?

**Comment by ebattat** [comment]
Close due to maintenance

**Pull request closed without merging**
