### PR TITLE
Update oc to cli

### PR DESCRIPTION
**Pull request by ebattat**
## Type of change
Note: Fill **x** in []
- [x] bug
- [ ] enhancement
- [ ] documentation
- [ ] dependencies

## Description

Update oc to cli

### CODE REVIEW

**Review by RobertKrawitz — CHANGES_REQUESTED** [review]
Good!  There are some others, though:
- create_kata.py (around lines 39 and 56)
- create_ocp_resource_operations.py (around lines 97 and 100)

**Comment by ebattat** [comment]
@RobertKrawitz,

This change is relevant only OC class and not to Operator class because the operators are relevant only to OCP and not k8s, I just change all the oc methods to use the same approach.

**Comment by RobertKrawitz** [comment]
Those others all use the OC class though; you might as well fix it all while you're at it.

**Comment by ebattat** [comment]
There is no need to change all other 'oc' commands because 'csv,' 'kata,' and 'odf' are only relevant to OpenShift. This means there is no need to use 'kubectl' commands instead of 'oc'.

**Comment by RobertKrawitz** [comment]
> @RobertKrawitz, We don't need it for OpenShift operators; we only use the 'oc' command for them

Yeah, OK, I'd prefer to keep it general, but I see the point.

**Review by RobertKrawitz — APPROVED** [review]

**Pull request merged**
